[package]
name = "SuperSnake"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies.amethyst]
version = "0.13.2"
git = "https://github.com/amethyst/amethyst.git"
features = ["vulkan","tiles","no-slow-safety-checks"]
